# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/lib_nbs/envs/POMDPs.ipynb.

# %% auto 0
__all__ = ['POMDP', 'Cyclic_Env', 'Noisy_Cycle']

# %% ../../nbs/lib_nbs/envs/POMDPs.ipynb 3
from .core import Abstract_Env
import numpy as np
from numpy.typing import NDArray

# %% ../../nbs/lib_nbs/envs/POMDPs.ipynb 4
class POMDP(Abstract_Env):
    """
    A general constructor for POMDPs
    """
    def __init__(self,
                 percepts: NDArray[np.int_],     #An SxK array where S is the number of Percepts and K is the number of categories for each percept. If 1d, converted to Sx1
                 observation_function: NDArray[np.float_], #An NxS array, where N is the number of states in the cycle and S is the number of possible percepts. Rows contain probability distributions
                 transition_function: NDArray[np.float_],  #An NxNxA array, where A is the number of actions. Rows in each slice contain probability distributions.
                 initial_state: int = 0                                                 #Start state of POMDP
                ):
        '''
        Checks validity of observation and transition function, assigns variables to self.
        '''
        assert isinstance(percepts, np.ndarray)
        if percepts.ndim == 1:
            percepts = percepts[:,np.newaxis]
        assert np.shape(percepts)[0] == np.shape(observation_function)[1]
        assert np.shape(transition_function)[0] == np.shape(observation_function)[0]
        assert np.shape(transition_function)[0] == np.shape(transition_function)[1]
        assert transition_function.ndim == 3
        assert np.isclose(np.sum(transition_function,axis =1), 1, atol=1e-9).all() #all rows sum to 1
        assert np.isclose(np.sum(observation_function,axis =1), 1, atol=1e-9).all() #all rows sum to 1
        assert initial_state in range(np.shape(observation_function)[0])
         
        self.percepts = percepts
        self.observation_function = observation_function
        self.transition_function = transition_function
        state = initial_state
        super().__init__(state = state)

    def transition(self, 
                   action: int
                   ):
        """
        randomly select a new state using transition probabilites from current state and action
        """
        if not action in range(np.shape(self.transition_function)[2]):
            raise ValueError("The action input for POMDP transition must be integer valued and within the scope of the transition function")
        transition_probs = self.transition_function[self.state,:, action]
        self.state = np.random.choice(len(transition_probs), p = transition_probs)

    def get_observation(self)->NDArray[np.int_]:
        """
        randomly select a percept using observation probabilites from current state
        """
        percept_probs = self.observation_function[self.state,:]
        percept_index = np.random.choice(len(percept_probs), p = percept_probs)
        return self.percepts[percept_index,:]

# %% ../../nbs/lib_nbs/envs/POMDPs.ipynb 10
class Cyclic_Env(POMDP):
    """
    An environment that cycles deterministically through a sequence of percepts that may be passed to an agent
    """
    def __init__(self,
                 percept_cycle: NDArray[np.int_],     #an N x K array, where N is the number of states in the cycles and K is the number of categories in a percept. If 1d, will be converted to Nx1
                 initial_state: int = 0,        #index of first percept returned by get_observation()
                 supress_warning: bool = False  #warns if Action != 0 is input to transition function
                ):
        '''
        Constructs deterministic transition function and observation from percept_cycle
        '''
        if percept_cycle.ndim == 1:
            percept_cycle = percept_cycle[:, np.newaxis]
        
        # Get unique rows and, for each row of percept_cycle, the index of its unique representative
        percepts, inverse = np.unique(percept_cycle, axis=0, return_inverse=True)
        
        # One-hot encode those indices to form the observation function
        observation_function = np.eye(percepts.shape[0], dtype=float)[inverse]       

        #create a cyclic shifted diagonal matrix
        S = np.shape(percept_cycle)[0]
        transition_function = np.roll(np.eye(N = S), shift = 1, axis = 1) 
        transition_function = transition_function[:,:,np.newaxis] #adds a dimension to allow for a single action
        
        super().__init__(percepts = percepts, observation_function = observation_function, transition_function = transition_function, initial_state = initial_state)
        self.supress_warning = supress_warning
        
    def transition(self, action:int):
        if not action == 0 and not self.supress_warning:
            print('Warning: Cyclic_Env is not action mediated. Action input has been converted to 0')
        action = 0
        super().transition(action)

# %% ../../nbs/lib_nbs/envs/POMDPs.ipynb 17
class Noisy_Cycle(POMDP):
    def __init__(self,
                 percepts: NDArray[np.int_],     #an SxK array where S is the number of Percepts and K is the number of categories for each percept
                                                                                        #if 1d, converted to Sx1
                 observation_function: NDArray[np.float_],  #An NxS array, where N is the number of states in the cycle and S is the number of possible percepts
                 initial_state: int = 0,
                 supress_warning: bool = False                                          #warns if Action != 0 is input to transition function
                ):
        if percepts.ndim == 1:
            percepts = percepts[:,np.newaxis]
            
        #create a cyclic shifted diagonal matrix for transition_function
        S = np.shape(observation_function)[0] #number of percepts
        transition_function = np.roll(np.eye(N = S), shift = 1, axis = 1) #creates 1-shifted identity matrix
        transition_function = transition_function[:,:,np.newaxis] #adds a dimension to allow for a single action

        super().__init__(percepts = percepts, observation_function = observation_function, transition_function = transition_function, initial_state = initial_state)
        self.supress_warning = supress_warning
        
    def transition(self, action:int):
        if not action == 0 and not self.supress_warning:
            print('Warning: Cyclic_Env is not action mediated. Action input has been converted to 0')
        action = 0
        super().transition(action)

    def get_stationary_entropy(self):
        """Calculates the stationary entropy of the observation function.
        
        Returns:
            float: The stationary entropy of the observation function.
        """
        stat_dist = 1/np.shape(self.observation_function)[0] #uniform stationary distribution in cycle
        
        # Calculate the stationary entropy
        obs_probs = np.dot(stat_dist, self.observation_function)
        stationary_entropy = -np.sum(obs_probs * np.log2(obs_probs + 1e-10))  # Adding a small constant to avoid log(0)
        
        return stationary_entropy
    
    def get_predictive_entropy(self):
        """Calculates the predictive entropy of the observation function.
        
        Returns:
            float: The predictive entropy of the observation function.
        """
        stat_dist = 1/np.shape(self.observation_function)[0] #uniform stationary distribution in cycle
        
        # Calculate the predictive entropy
        predictive_entropy = 0
        for i in range(np.shape(self.observation_function)[0]):
            obs_probs = self.observation_function[i, :]
            masked_probs = obs_probs[obs_probs > 0]  # Filter out zero probabilities
            predictive_entropy += stat_dist * (-np.sum(masked_probs * np.log2(masked_probs)))  # Adding a small constant to avoid log(0)
        
        return predictive_entropy
