# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/lib_nbs/methods/01_transforms.ipynb.

# %% auto 0
__all__ = ['decay_toward_uniform', 'decay_toward_stationary', 'logit_bias']

# %% ../../nbs/lib_nbs/methods/01_transforms.ipynb 2
import numpy as np
def _softmax(beta, x):
        """
        Given an input, calculates the normalized exponential function.
        """
        # rescale exponential to avoid large numbers
        rescale = max(x)
        exp_x = np.exp(beta *(x-rescale))
        # get normalization
        norm = sum(exp_x)
        # calculate normalized exponential
        softmax_x = exp_x/norm

        return softmax_x

# %% ../../nbs/lib_nbs/methods/01_transforms.ipynb 4
def _logistic(x, L:float = 1,k:float = 1,x_shift = 0,y_shift:float = 0):
    return L/(1 + np.exp(-k*(x-x_shift))) + y_shift

# %% ../../nbs/lib_nbs/methods/01_transforms.ipynb 6
def _exponentiated_shift(x, k, epsilon = 0.0001):
    return (x + epsilon) ** (np.exp(-k)) / ((1 + 2*epsilon) ** (np.exp(-k)))

# %% ../../nbs/lib_nbs/methods/01_transforms.ipynb 8
import numpy as np
def _decay_toward_uniform(pmfs: np.ndarray, alphas: np.ndarray) -> np.ndarray:
    """
    Apply decay toward uniform distribution for each row of a batch of PMFs,
    with a potentially different alpha per column.

    Args:
        pmfs: Array of shape (K, N), where each column is a PMF summing to 1.
        alphas: Array of shape (N,), or scalar in shape (1,) or (), each alpha ∈ [0, 1].

    Returns:
        Array of shape (K, N), where each column is decayed toward uniform.
    """
    if pmfs.ndim == 1:
        pmfs = pmfs[np.newaxis,:]  # Convert to shape (1,K)

    if not np.allclose(pmfs.sum(axis=1), 1, atol=1e-9):
        raise ValueError("All rows in pmfs must sum to one")

    N = pmfs.shape[0]

    if np.isscalar(alphas) or alphas.shape == (1,):
        alphas = np.full((N,), float(alphas))
    
    if not np.all((0 <= alphas) & (alphas <= 1)):
        raise ValueError("All alphas must be between 0 and 1")

    K = pmfs.shape[1]
    uniform = np.full((N, K), 1 / K)
    alphas = alphas[:,np.newaxis]  # Ensure broadcasting over rows
    new_pmfs = (1 - alphas) * pmfs + alphas * uniform
    return new_pmfs

# %% ../../nbs/lib_nbs/methods/01_transforms.ipynb 10
import numpy as np
def decay_toward_uniform(pmfs: np.ndarray, alphas: np.ndarray) -> np.ndarray:
    """
    Apply decay toward uniform distribution for each row of a batch of PMFs,
    with a potentially different alpha per column.

    Args:
        pmfs: Array of shape (K, N), where each column is a PMF summing to 1.
        alphas: Array of shape (N,), or scalar in shape (1,) or (), each alpha ∈ [0, 1].

    Returns:
        Array of shape (K, N), where each column is decayed toward uniform.
    """
    if pmfs.ndim == 1:
        pmfs = pmfs[np.newaxis,:]  # Convert to shape (1,K)

    if not np.allclose(pmfs.sum(axis=1), 1, atol=1e-9):
        raise ValueError("All rows in pmfs must sum to one")

    N = pmfs.shape[0]

    if np.isscalar(alphas) or alphas.shape == (1,):
        alphas = np.full((N,), float(alphas))
    
    if not np.all((0 <= alphas) & (alphas <= 1)):
        raise ValueError("All alphas must be between 0 and 1")

    K = pmfs.shape[1]
    uniform = np.full((N, K), 1 / K)
    alphas = alphas[:,np.newaxis]  # Ensure broadcasting over rows
    new_pmfs = (1 - alphas) * pmfs + alphas * uniform
    return new_pmfs

# %% ../../nbs/lib_nbs/methods/01_transforms.ipynb 16
from numpy.typing import NDArray
def decay_toward_stationary(pmfs: NDArray[np.float_],                      #Array of shape (N, K) or (K,), where each row sums to 1.
                             gammas: NDArray[np.float_]|float,                    #Array of shape (N,), or scalar in shape (1,) or (), each gamma ∈ [0, 1].
                             stationary_distribution: NDArray[np.float_]    #Row vector of shape (K,) (sums to 1) used as the target mix.

                             ) -> NDArray[np.float_]:
    """
    Decay each row-PMF toward a given stationary distribution.
    Returns:
        Array of shape (N, K), where each row is mixed with stationary_distribution.
        new_pmfs = (1 - gamma_i) * pmfs[i, :] + gamma_i * stationary_distribution
    """
    # Ensure 2D with rows as PMFs
    if pmfs.ndim == 1:
        pmfs = pmfs[np.newaxis, :]  # (1, K)
    elif pmfs.ndim != 2:
        raise ValueError("pmfs must be 1D or 2D (rows are PMFs).")

    # Basic validity: rows sum to 1
    if not np.allclose(pmfs.sum(axis=1), 1.0, atol=1e-9):
        raise ValueError("All rows in pmfs must sum to 1.")

    N, K = pmfs.shape

    # Validate and shape stationary distribution
    sd = np.asarray(stationary_distribution).squeeze()
    if sd.ndim != 1 or sd.shape[0] != K:
        raise ValueError(f"stationary_distribution must be shape ({K},), got {sd.shape}.")
    if np.any(sd < 0):
        raise ValueError("stationary_distribution must be nonnegative.")
    if not np.allclose(sd.sum(), 1.0, atol=1e-9):
        raise ValueError("stationary_distribution must sum to 1.")
    sd = np.broadcast_to(sd, (N, K))  # same stationary row for all rows

    # Validate and broadcast gammas
    if np.isscalar(gammas) or (isinstance(gammas, np.ndarray) and gammas.shape == (1,)):
        gammas = np.full((N,), gammas)
    else:
        gammas = np.asarray(gammas)
        if gammas.ndim == 2 and gammas.shape == (N, 1):
            gammas = gammas.ravel()
        if gammas.shape != (N,):
            raise ValueError(f"gammas must be scalar or shape ({N},), got {gammas.shape}.")

    if not np.all((0.0 <= gammas) & (gammas <= 1.0)):
        raise ValueError("All gammas must be in [0, 1].")

    gammas = gammas[:, np.newaxis]  # (N, 1) for broadcasting over columns

    # Mix toward stationary distribution
    new_pmfs = (1.0 - gammas) * pmfs + gammas * sd
    return new_pmfs

# %% ../../nbs/lib_nbs/methods/01_transforms.ipynb 20
def logit_bias(rate, bias):
    if isinstance(rate, np.ndarray):
        assert np.issubdtype(rate.dtype, np.floating)
    else:
        assert isinstance(rate, (float, np.floating))
        rate = np.array(rate)
    if np.any(rate < 0) or np.any(rate > 1):
        raise ValueError("rate in logit_bias transformation must be between 0 and 1")
    if isinstance(bias, np.ndarray):
        assert np.issubdtype(bias.dtype, np.floating)
    else:
        assert isinstance(bias, (int, float, np.floating, np.integer))
        bias = np.array(bias)
        
    #broadcast if either rate or bias given as scalar
    if rate.size == 1:
        rate = np.full_like(bias, rate.item())
    elif bias.size == 1:
        bias = np.full_like(rate, bias.item())
    # Check if arrays can be compared element-wise
    if rate.shape != bias.shape:
        raise ValueError(f"Array shapes do not match: {rate.shape} vs {bias.shape}")

    #set up mask for 0 and 1 edge cases
    mask = (rate == 0) | (rate == 1)
    new_rate = rate.copy() #intialize new variable for transform
    new_rate[~mask] = np.log2(rate[~mask]/(1-rate[~mask])) + bias[~mask] #add bias in logit space
    new_rate[~mask] = 1/(1 + 2**-new_rate[~mask]) #reverse sigmoid
    return new_rate    

# %% ../../nbs/lib_nbs/methods/01_transforms.ipynb 22
def _logit_bias(rate, bias):
    if isinstance(rate, np.ndarray):
        assert np.issubdtype(rate.dtype, np.floating)
    else:
        assert isinstance(rate, (float, np.floating))
        rate = np.array(rate)
    if np.any(rate < 0) or np.any(rate > 1):
        raise ValueError("rate in logit_bias transformation must be between 0 and 1")
    if isinstance(bias, np.ndarray):
        assert np.issubdtype(bias.dtype, np.floating)
    else:
        assert isinstance(bias, (int, float, np.floating, np.integer))
        bias = np.array(bias)
        
    #broadcast if either rate or bias given as scalar
    if rate.size == 1:
        rate = np.full_like(bias, rate.item())
    elif bias.size == 1:
        bias = np.full_like(rate, bias.item())
    # Check if arrays can be compared element-wise
    if rate.shape != bias.shape:
        raise ValueError(f"Array shapes do not match: {rate.shape} vs {bias.shape}")

    #set up mask for 0 and 1 edge cases
    mask = (rate == 0) | (rate == 1)
    new_rate = rate.copy() #intialize new variable for transform
    new_rate[~mask] = np.log2(rate[~mask]/(1-rate[~mask])) + bias[~mask] #add bias in logit space
    new_rate[~mask] = 1/(1 + 2**-new_rate[~mask]) #reverse sigmoid
    return new_rate    
